services:
  backend:
    image: api-server
    container_name: "${PROJECT_NAME}-backend"
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      mongo:
        condition: service_healthy
    ports:
      - 9080:9080

  mongo:
    image: mongo:4.2.0
    container_name: "${PROJECT_NAME}-db"
    healthcheck:
      test: echo 'db.stats().ok' | mongo localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_INITDB_DATABASE=app
    ports:
      - 27017:27017
    volumes:
      - /opt/mongodata:/data/db

